config/routes.rb
Rails.application.routes.draw do
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	mount Ckeditor::Engine => '/ckeditor'

	namespace :admin do

		get '/dashboard' => 'home#index'
		root to: 'sessions#new'
		get '/login' => 'sessions#new'
		post '/login' => 'sessions#create'
		get '/logout' => 'sessions#destroy'

		resources :users
		resources :user_roles
	end
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :user_role
  	belongs_to :status_user
  	has_one :address, dependent: :destroy
  	has_many :orders, dependent: :destroy

  	has_secure_password
  	validates :first_name, presence: true
  	validates :last_name, presence: true
	validates :email, uniqueness: true, presence: true

	def user_role
		UserRole.find_by(id: self.user_role_id)
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
	before_action :authorize_session
    before_action :set_user, only: [:show, :edit, :update]
    before_action :set_s3_direct_post

    def index
        users = Admin::UserDatatable.new(params, view_context: view_context)
        @users = users.get_raw_records
        respond_to do |format|
            format.html
            format.json { render json:  users}
        end
    end

    def show
    end

    def new
        @user = User.new
        @user.build_address
    end

    def create
        @user = User.new(user_params)
        respond_to do |format|
            if @user.save
            	if @user.build_address(address_params).save
                	format.html { redirect_to "/admin/users", notice: 'Usuário criado com sucesso!' }
                end
            else
                format.html { render :new }
                format.json { render json: @user.errors.full_messages, status: :unprocessable_entity }
            end
        end
    end

    def edit
    end

    def update
        respond_to do |format|
            if @user.update(user_params)
            	if @user.address.update(address_params)
                	format.html { redirect_to "/admin/users", notice: 'Usuário atualizado com sucesso!' }
            	end
            else
                format.html { render :edit }
            end
        end
    end

    def destroy_multiple
        params[:user_ids].each do |id|
            User.find_by(id: id).destroy
        end
    end

    def sendEmailActivationUser
        if @user
            begin
            UserMailer.activation(@user).deliver_now
            flash[:notice] = 'Email reenviado'
            @user.status = "active"
            rescue Net::SMTPAuthenticationError, Net::SMTPServerBusy, Net::SMTPSyntaxError, Net::SMTPFatalError, Net::SMTPUnknownError => e
            flash[:notice] = nil
            flash[:error] = "Erro ao enviar o Email!"
            @user.status = "inactive"
            end
            redirect_to @user
        end
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:user_ids, :id, :avatar, :first_name, :last_name, :date_of_birth, :email, :status_user_id, :user_role_id, :password, :password_confirmation)
    end

    def address_params
    	params.required(:address).permit(:id, :address, :address_number, :complement, :neighborhood, :cep, :city, :state, :user_id)
    end

    def set_s3_direct_post
        @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read', content_type:'Content-Type')
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

	def edit_user(user)
		'/admin/users/#user.id/edit'
	end
end

app/views/admin/users/_favorite_fields.html.erb
<div class="nested-fields" >
    <div class="form-row">
        <div class="form-group col-md-6 required-field">
            <label class="active">Produto</label>
            <%= f.collection_select(:product_id, Product.all, :id, :name) %>
        </div>
        <div class="form-group col-md-6" style="margin-top: 2%;">
            <%= link_to_remove_association "APAGAR FAVORITO", f, class:"waves-effect waves-light btn right-align" %>
        </div>
    </div>
</div>

app/views/admin/users/_form.html.erb
<div class="wrapper ">   
    <%= render 'layouts/admin/sidebar' %>
    <div class="content">       
        <%= render 'layouts/admin/navbar' %>        
        <%= render 'layouts/admin/flash_messages' %>
        <%= form_for([:admin,@user], html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
            <% if @user.errors.any? %>
                <div id="error_explanation">
                    <ul>
                        <% @user.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            <div class="row">
                <div class="col-md-8" style="margin: auto">
                    <div class="card card-user">
                        <div class="card-header">
                            <h5 class="card-title">Usuário</h5>
                        </div>
                        <div class="card-body">
                            <form>
                                <div class="form-row">
                                    <div class="form-group col-md-6 required-field">
                                        <label>Nome</label>
                                        <%= f.text_field :first_name, required:true, class:"form-control", placeholder: ""%>
                                    </div>
                                    <div class="form-group col-md-6 required-field">
                                        <label>Sobrenome</label>
                                        <%= f.text_field :last_name, required:true, class:"form-control", placeholder: ""%>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-4 required-field">
                                        <label>Email</label>
                                        <%= f.text_field :email, :required => true, class:"form-control", placeholder: "" %>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label>Data de Nascimento</label>
                                        <%= f.text_field :date_of_birth, class:"form-control datepicker", placeholder: ""%>
                                    </div>
                                    <div class="col-md-4" id="file_upload">
                                        <label>Imagem de Perfil</label>
                                        <%= f.file_field :avatar, id: :user_file_url,  accept:"image/png,image/jpeg", style:'font-size: 70%;'%>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6 required-field">
                                        <label>Senha</label>
                                        <%= f.password_field :password, :required => true, class:"form-control", placeholder: ""%>
                                    </div>
                                    <div class="form-group col-md-6 required-field">
                                        <label>Confirmar Senha</label>
                                        <%= f.password_field :password_confirmation, :required => true, class:"form-control", placeholder: "" %>
                                    </div>
                                </div>

                                <div class="form-row">
                                    <div class="form-group col-md-6 required-field">
                                        <label>Status</label>
                                        <%= f.collection_select(:status_user_id, StatusUser.all, :id, :name) %>
                                    </div>
                                    <div class="form-group col-md-6 required-field">
                                        <label>Permissão</label>
                                        <%= f.collection_select(:user_role_id, UserRole.all, :id, :name) %>
                                    </div>
                                </div>
                                
                                <nav class="navbar navbar-light navbar_hr">
                                    <span class="navbar-text text_hr">
                                       ENDEREÇO PARA USUÁRIO
                                    </span>
                                </nav>

                                <%= fields_for :address do |u| %>
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>Endereço</label>
                                            <%= u.text_field :address, class:"form-control", placeholder: ""%>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>Número</label>
                                            <%= u.text_field :address_number, class:"form-control", placeholder: "" %>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>Complemento</label>
                                            <%= u.text_field :complement, class:"form-control", placeholder: "" %>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>Bairro</label>
                                            <%= u.text_field :neighborhood, class:"form-control", placeholder: ""%>
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>cep</label>
                                            <%= u.text_field :cep, class:"form-control", placeholder: "" %>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-4">
                                            <label>Estado</label>
                                            <%= u.text_field :state, class:"form-control", placeholder: "" %>
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>Cidade</label>
                                            <%= u.text_field :city, class:"form-control", placeholder: "" %>
                                        </div>
                                    </div>
                                <% end %>

                                <div class="form-row">
                                    <div class="input-field update ml-auto mr-auto">
                                        <%= f.button :submit, class:"btn btn-primary btn-round" do %>
                                        <i class="fas fa-globe-americas"></i> Criar/Atualizar
                                        <% end %>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/admin/users/edit.html.erb
<div class="wrapper ">   
    <%= render 'layouts/admin/sidebar' %>
    <div class="content">       
        <%= render 'layouts/admin/navbar' %>        
        <%= render 'layouts/admin/flash_messages' %>
        <%= form_for([:admin,@user], html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
            <% if @user.errors.any? %>
                <div id="error_explanation">
                    <ul>
                        <% @user.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            <div class="row">
                <div class="col-md-8" style="margin: auto">
                    <div class="card card-user">
                        <div class="card-header">
                            <h5 class="card-title">Usuário</h5>
                        </div>
                        <div class="card-body">
                            <form>
                                <div class="form-row">
                                    <div class="form-group col-md-6 required-field">
                                        <label>Nome</label>
                                        <%= f.text_field :first_name, required:true, class:"form-control", placeholder: ""%>
                                    </div>
                                    <div class="form-group col-md-6 required-field">
                                        <label>Sobrenome</label>
                                        <%= f.text_field :last_name, required:true, class:"form-control", placeholder: ""%>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-4 required-field">
                                        <label>Email</label>
                                        <%= f.text_field :email, :required => true, class:"form-control", placeholder: "" %>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label>Data de Nascimento</label>
                                        <%= f.text_field :date_of_birth, class:"form-control datepicker", placeholder: ""%>
                                    </div>
                                    <div class="col-md-4" id="file_upload">
                                        <label>Imagem de Perfil</label>
                                        <%= f.file_field :avatar, id: :user_file_url,  accept:"image/png,image/jpeg", style:'font-size: 70%;'%>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6 required-field">
                                        <label>Senha</label>
                                        <%= f.password_field :password, :required => true, class:"form-control", placeholder: ""%>
                                    </div>
                                    <div class="form-group col-md-6 required-field">
                                        <label>Confirmar Senha</label>
                                        <%= f.password_field :password_confirmation, :required => true, class:"form-control", placeholder: "" %>
                                    </div>
                                </div>

                                <div class="form-row">
                                    <div class="form-group col-md-6 required-field">
                                        <label>Status</label>
                                        <%= f.collection_select(:status_user_id, StatusUser.all, :id, :name) %>
                                    </div>
                                    <div class="form-group col-md-6 required-field">
                                        <label>Permissão</label>
                                        <%= f.collection_select(:user_role_id, UserRole.all, :id, :name) %>
                                    </div>
                                </div>
                                
                                <nav class="navbar navbar-light navbar_hr">
                                    <span class="navbar-text text_hr">
                                       ENDEREÇO PARA USUÁRIO
                                    </span>
                                </nav>

                                <%= fields_for :address do |u| %>
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>Endereço</label>
                                            <% if !@user.address.address %> 
                                            	<%= u.text_field :address, class:"form-control", placeholder: ""%>
                                            <% else %>
												<%= u.text_field :address, value: @user.address.address, class:"form-control", placeholder: ""%>
                                            <% end %>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>Número</label>
                                            <% if !@user.address.address_number %>
                                            	<%= u.text_field :address_number, class:"form-control", placeholder: "" %>
                                            <% else %>
												<%= u.text_field :address_number, value: @user.address.address_number, class:"form-control", placeholder: "" %>
                                            <% end %>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>Complemento</label>
                                            <% if !@user.address.complement %>
                                            	<%= u.text_field :complement, class:"form-control", placeholder: "" %>
                                            <% else %>
												<%= u.text_field :complement, value: @user.address.complement, class:"form-control", placeholder: "" %>
                                            <% end %>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>Bairro</label>
                                            <% if !@user.address.neighborhood %>
                                            	<%= u.text_field :neighborhood, class:"form-control", placeholder: ""%>
                                            <% else %>
												<%= u.text_field :neighborhood, value: @user.address.neighborhood, class:"form-control", placeholder: ""%>
                                            <% end %>
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>cep</label>
                                            <% if !@user.address.cep %>
                                            	<%= u.text_field :cep, class:"form-control", placeholder: "" %>
                                            <% else %>
												<%= u.text_field :cep, value: @user.address.cep, class:"form-control", placeholder: "" %>
                                            <% end %>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>Estado</label>
                                            <% if !@user.address.state %>
                                            	<%= u.text_field :state, class:"form-control", placeholder: "" %>
                                            <% else %>
												<%= u.text_field :state, value: @user.address.state, class:"form-control", placeholder: "" %>
                                            <% end %>
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Cidade</label>
                                            <% if !@user.address.city %>
                                            	<%= u.text_field :city, class:"form-control", placeholder: "" %>
                                            <% else %>
												<%= u.text_field :city, value: @user.address.city, class:"form-control", placeholder: "" %>
                                            <% end %>
                                        </div>
                                    </div>
                                <% end %>

                                <div class="form-row">
                                    <div class="input-field update ml-auto mr-auto">
                                        <%= f.button :submit, class:"btn btn-primary btn-round" do %>
                                        <i class="fas fa-globe-americas"></i> Atualizar
                                        <% end %>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/admin/users/index.html.erb
<div class="wrapper ">
    <%= render 'layouts/sidebar' %>
    <div class="content">       
        <%= render 'layouts/navbar' %>        
        <%= render 'layouts/flash_messages' %>
            <div class="row ml-auto mr-auto">
                <div class="col-md-10 mr-auto ml-auto">
                    <div class="card">
                        <div class="card-header" style="display: inline;">
                            <h4 class="card-title" style="display: inline;">    Usuários 
                                <span style="float: right"><%= @users.count %></span>
                            </h4>
                            <a href="/admin/users/new" style="margin-left: 2%; color: #51cbce;">
                                <i class="fa fa-plus"></i>
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive table-striped">
                                <table style="width: 100%;" id="datatable" data-source="<%= admin_users_path(format: :json) %>">
                                    <thead>
                                        <tr>
                                            <th>Todos<input type="checkbox" id="select_all" name="select_invoice" /></th>
                                            <th>Nome</th>
                                            <th>Email</th>
                                            <th>Data de Nascimento</th>
                                            <th>Status</th>
                                            <th>Editar</th>
                                         </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                            <button type="button" id="remove">Deletar!</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script> 
var table = null;
document.addEventListener("turbolinks:before-cache", function() {
  if (table !== null) {
   table.destroy()
   table = null
  }
});
//Configuring datatable
var table = $('#datatable').DataTable({
            processing: true,
            fixedHeader: true,
            keys: true,
            responsive: true,
            scrollY:        300,
            deferRender:    true,
            scroller:       true,
            dom: 'Bfrtip',
            buttons: [
                'copy', 'excel', 'pdf'
            ],
            serverSide: true,
            stateSave: true,
            language: {
            url: "//cdn.datatables.net/plug-ins/1.10.19/i18n/Portuguese-Brasil.json"
            },
            ajax: {
                "url": $('#datatable').data('source')
            },
            pagingType: "full_numbers",
            columns: [        
                {"data": ""},
                {"data": "name"},
                {"data": "email"},
                {"data": "bday"},
                {"data": "status_id"},
                {"defaultContent": '<button>Editar</button>'},
            ],
            columnDefs: [{
              orderable: false,
              className: 'select-checkbox',      
              targets: 0
            },
            {
                targets: 0,
                defaultContent: '',
                visible: true,      
                orderable : false,
                searchable: false,
            },
            {
                targets: 5,
                className: 'edit-data',      
                orderable: false,
            },
            {
                targets: 1,
                className: 'show-link',
            },
            ],
            select: {
                style:    'multi',
                selector: 'td:first-child'
            },            
            order: [[1,'asc']],
});

//Select All
$('#datatable').on('click', '#select_all', function() {
    if ($('#select_all:checked').val() === 'on') {
      table.rows().select();
    }
    else {
      table.rows().deselect();
    }      
});  

//Delete selected items
$('#remove').click(function() {
    if( $('.selected').length > 0) { 
        var user_ids = [];
        $('.selected').each(function() {
            user_ids.push(table.row( this ).id());
        });

        $.ajax({
             async: false,
             global: false,
             data: {user_ids: user_ids},
             url: "/admin/destroy_multiple_users",
             type: 'post'
        });
        table.ajax.reload();
    }
});

$('#datatable').on('click', '.edit-data', function() {
    let id = table.row( this ).id();
    window.location = '/admin/users/'+id+"/edit";
});

</script>

app/views/admin/users/show.html.erb
<div class="wrapper ">
    <%= render 'layouts/admin/sidebar' %>
    <div class="content">       
        <%= render 'layouts/admin/navbar' %>        
        <%= render 'layouts/admin/flash_messages' %>
        <div class="row" >
            <a href="/admin/users/<%= @user.id %>/edit" class="a__new--float">
              <i class="fa fa-pencil" style="margin: 24px;"></i>
            </a>
            <div class="col-md-10 mr-auto ml-auto">
                <div class="card card-user">
                    <div class="image">
                        <img src="/assets/images/damir-bosnjak.jpg" alt="...">
                    </div>
                    <div class="card-body">
                        <div class="author">
                                <% if !@user.avatar %>
                                    <img class="avatar border-gray" src="/assets/images/mike.jpg" alt="...">
                                <% else %>
                                    <img class="avatar border-gray" src="<%= @user.avatar %>" >
                                <% end %>
                                <h5 class="title"><%= @user.name %></h5>
                            <p class="description--black">
                                <i class="fa fa-envelope" style="margin-right:2%"></i>
                                <%= @user.email %>
                            </p>
                        </div>
                    </div>
                    <div class="card-footer">
                        <hr>
                        <div class="button-container">
                            <div class="row">
                                <div class="ml-auto mr-auto">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>  
</div>